service: import-service

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-2

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource: 
        - "arn:aws:s3:::aws-shop-import-service-bucket"
    - Effect: "Allow" 
      Action: 
        - "s3:*"
      Resource:
        - "arn:aws:s3:::aws-shop-import-service-bucket/*"

functions: 
  importProductsFile:
    handler: handler/importProductsFile.main
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler/importFileParser.main
    events:
      - s3:
          bucket: aws-shop-import-service-bucket
          event: s3:ObjectCreated:*
          rules: 
            - prefix: uploaded/
          existing: true